apiVersion: v1
kind: Service
metadata:
  name: cefis-studios-app
spec:
  ports:
    - port: 3000
  type: NodePort
  selector:
    app: cefis-studios-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cefis-studios-app
  labels:
    app: cefis-studios-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cefis-studios-app
  template:
    metadata:
      labels:
        app: cefis-studios-app
    spec:
      imagePullSecrets:
        - name: dockerhubcred
      containers:
        - name: cefis-studios-app
          image: cefis/autonomous-studios
          resources:
            limits:
              memory: 128Mi
              cpu: 50m
            requests:
              memory: 128Mi
              cpu: 50m
          ports:
          - containerPort: 3000
